tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "primary-fixed-dim": "#86d7ad",
                "on-tertiary-fixed-variant": "#623f18",
                "primary-fixed": "#a1f4c8",
                "on-secondary": "#ffffff",
                "tertiary-fixed": "#ffdcbd",
                "tertiary-fixed-dim": "#f0bd8b",
                "on-primary-container": "#f5fff6",
                "on-tertiary": "#ffffff",
                "surface-variant": "#e3e3d6",
                "surface-container-low": "#f4f4e7",
                "surface-container-highest": "#e3e3d6",
                "secondary-fixed": "#ffdbcc",
                "primary": "#0b6947",
                "on-primary-fixed-variant": "#005236",
                "outline-variant": "#bec9c0",
                "on-secondary-fixed": "#311305",
                "on-secondary-container": "#7a4f3c",
                "inverse-primary": "#86d7ad",
                "secondary-container": "#ffc5ac",
                "surface": "#fafaec",
                "on-error-container": "#93000a",
                "secondary-fixed-dim": "#f3baa2",
                "on-tertiary-fixed": "#2c1600",
                "surface-container-lowest": "#ffffff",
                "secondary": "#7f5440",
                "on-tertiary-container": "#fffbff",
                "inverse-on-surface": "#f1f2e4",
                "surface-container-high": "#e9e9db",
                "error": "#ba1a1a",
                "error-container": "#ffdad6",
                "surface-container": "#eeefe1",
                "on-surface": "#1a1c14",
                "tertiary": "#7b542b",
                "on-background": "#1a1c14",
                "background": "#fafaec",
                "surface-dim": "#dadbcd",
                "outline": "#6f7a72",
                "on-error": "#ffffff",
                "on-primary": "#ffffff",
                "primary-container": "#30835f",
                "on-surface-variant": "#3f4943",
                "surface-tint": "#116c4a",
                "inverse-surface": "#2f3128",
                "on-secondary-fixed-variant": "#643d2b",
                "tertiary-container": "#966c41",
                "surface-bright": "#fafaec",
                "on-primary-fixed": "#002113"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "fontFamily": {
                "headline": ["Space Grotesk", "sans-serif"],
                "body": ["Manrope", "sans-serif"],
                "label": ["Manrope", "sans-serif"]
            }
        },
    },
};
